apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - zones.dns.cav.enablers.ob.yaml
  - clusterzones.dns.cav.enablers.ob.yaml
  - rrsets.dns.cav.enablers.ob.yaml
  - clusterrrsets.dns.cav.enablers.ob.yaml
