apiVersion: v1
kind: ServiceAccount
metadata:
  name: pdns-operator
  namespace: dns
  labels:
    app.kubernetes.io/name: pdns-operator
    app.kubernetes.io/component: dns-operator
automountServiceAccountToken: true
