apiVersion: v1
kind: Service
metadata:
  name: pdns-operator-metrics
  namespace: dns
  labels:
    app.kubernetes.io/name: pdns-operator
    app.kubernetes.io/component: dns-operator
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pdns-operator
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
